{
"hello" : "Hello","Bonjour","Hola","olá"
"banking" : "Banking","Bancaire","Bancario","Bancário"
"transfer" : "Transfer","Transfert","Transferir","Transferir"
"accOpening" : "Account Opening","Ouverture de compte","Apertura de cuenta","Abertura de conta"
"utilPayment" : "Utility Payments","Paiements des services publics","Pagos de servicios públicos","Pagamentos de serviços públicos"
"govPayment" : "Government Payments","Paiements gouvernementaux","Pagos del gobierno","Pagamentos do governo"
"cardTopup" : "Card Topup","Recharge de carte","Recarga de tarjeta","Recarga de cartão"
"cardHistory" : "Card History","Historique de la carte","Historial de la tarjeta","Histórico do Cartão"
"newPin" : "New Pin","Nouvelle épingle","Pin nuevo","Novo pino"
"cardBlock" : "Card Block","Bloc de carte","Bloque de tarjeta","Bloco de cartão"
"acc" : "Account","Compte","Cuenta","Conta"
"statement" : "Statement", "Déclaration","Declaración","Declaração"
"search" : "Search","Rechercher","Buscar","Procurar"
"addUser" : "Add User","Ajouter un utilisateur", "Agregar usuario","Adicionar usuário"
"addAcc" : "Add Account","Ajouter un compte","Añadir cuenta","Adicionar Conta"
"ownAcc" : "Same Bank Transfer","Propre compte","Cuenta propia","Conta própria"
"thirdParty" : "Third Party","Tierce personne","Tercero","Terceiro"
"toMob" : "To Mobile No","Vers mobile Non","Al número de móvil","Para Celular Não"
"virtualId" : "Virtual Id","Identifiant virtuel","identificación virtual","Identificação virtual"
"fd" : "Fixed Deposit","Compte fixe","Cuenta fija","Conta Fixa"
"savings" : "Recurring Deposit", "Compte épargne","Cuenta de ahorros","Conta Poupança"
"savingsBank" : "Savings Bank","Caisse d'épargne","Caja de Ahorros","caixa econômica"
"daily" : "Daily Deposit", "Dépôt quotidien","Depósito Diario","Depósito diário"
"currentAcc" : "Current Accounts","Compte courant","Cuentas actuales","Contas Correntes"
"recharge" : "Recharge","Recharger","Recargar","Recarrega"
"dish" : "Dish TV","Télévision parabolique","plato de televisión","TV parabólica"
"electricity" : "Electricity","Électricité","Electricidad","Eletricidade"
"water" : "Water bill","Facture d'eau","Factura de agua","Conta de água"
"shopping" : "Shopping","Achats","Compras","Compras"
"tax" : "Taxes","Impôts","Impuestos","impostos"
"customPayment" : "Custom Duties","Droits de douane","Derechos de aduana","Direitos Aduaneiros"
"schoolFee" : "School Fee","Frais scolaires","Cuotas escolares","Taxa Escolar"
"hospitalBill" : "Hospital Bills","Factures d'hôpital","Cuentas del hospital","Contas Hospitalares"
"rechargePayBills" : "Recharge & Pay Bills","Rechargez et payez vos factures","Recargar y pagar facturas","Recarregar e pagar contas"
"postpaid" : "Postpaid","Port payé","pospago","pós-pago"
}
